### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by MattAJ26** [MattAJ26/holistic-healing#20]
as a user I want to be able to view a homepage with brief descriptions about the company, owner, and services with navbar and footer

It is done when I can see the content displayed in a pleasant style.

![homepage](https://github.com/user-attachments/assets/2a5b24bc-e621-4560-98b4-c364423dca73)

**Comment by MarynaMartseniuk** [comment]
Add one more section on a Home page:

user story:
as a user I would like to see a reviews of other customers when I visit a Home page
as a developer I would like to add e review section at the bottom of the Home page where user can check on a reviews.

acceptance criteria:
it is done when user can see a Review section at the end of Home page (above the Footer) and able to check all reviews.

assigned to:
1. Olivier - functionality (1st step)
2. Maryna - styling (2nd step)
